//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab6.data.db.prejectsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int project_id { get; set; }
        public string project_name { get; set; }
        public Nullable<decimal> budget { get; set; }
        public int cust_id { get; set; }
        public int status_id { get; set; }
        public string description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProjectStatus ProjectStatus { get; set; }
    }
}
